kind: route
name: "default"
spec:
  routes:
    - routeForActivity: "retrieve resources"
      start: "ST"
      end: "W"
      duration: 3
    - routeForActivity: "retrieve resources"
      start: "ST"
      end: "Al"
      duration: 3
    - routeForActivity: "Sent to assembly station"
      start: "ST"
      end: "A"
      duration: 3
    - routeForActivity: "Back to stock"
      start: "A"
      end: "ST"
      duration: 3
    - routeForActivity: "Back to stock"
      start: "W"
      end: "ST"
      duration: 3
    - routeForActivity: "Sent to assembly station"
      start: "W"
      end: "A"
      duration: 3
    - routeForActivity: "Back to machine"
      start: "A"
      end: "W"
      duration: 3
    - routeForActivity: "Back to stock"
      start: "Al"
      end: "ST"
      duration: 3
    - routeForActivity: "Sent to assembly station"
      start: "Al"
      end: "A"
      duration: 3
    - routeForActivity: "Back to machine"
      start: "A"
      end: "Al"
      duration: 3