kind: object
name: "barResource"
spec:
  name: "barResource"
  type: "resource"
  input:
    - object: "order"
      number: 1
      lastState: ""
      size:
  size:
    length: "5"
    width: ""
    depth: ""