kind: datasource
name: "TransportSA"
spec:
  name: "TransportSA"
  group: "transport"
  type: objectCentric
  workforce: hasWorkforce
  workstation: "R"
  start: "ST"
  end: "A"
  selection: genericProbability
  distribution: [1.0]
  input:
    - object: "screw"
      number: 13
      lastState: ""
      size:
  workforces:
    - workforce: "transportRobot"
      number: 1
  eventData:
    - activity:
        name: "transport from stock to assembly"
        output:
          - object: "screw"
            number: 13
            change: ""
            size:
          - object: "handoverStock"
            number: 1
            change: ""
            size:
      transition: "Assembly"
      duration: 10
