kind: datasource
name: "DrillingBar"
spec:
  name: "DrillingBar"
  group: "factory"
  selection: genericProbability
  distribution: [1.0]
  input:
    - object:
      name: "bar"
      number: 1
  eventData:
    - activities:
      - activity: "Drilled"
        transition: "SandingBar"
        duration: 5
        output:
          - object:
            name: "bar"
            number: 1