kind: datasource
name: "SandingBarA"
spec:
  name: "SandingBarA"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "barA"
      number: 1
      lastState: "drilled"
      size:
        length: "2"
        width: ""
        depth: ""
  eventData:
    - activity: "Sanded"
      type: oc
      output:
        - object: "barA"
          number: 1
          change: "sanded"
          size:
            length: "2"
            width: ""
            depth: ""
      transition: "Assembly1"
      duration: 2
