kind: datasource
name: "OrderPlacementa"
spec:
  name: "OrderPlacementa"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "earringOrder"
      number: 1
      lastState: ""
      size:
  eventData:
    - activity: "order for resources"
      type: oc
      output:
        - object: "earringResourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStocka"
      duration: 0