kind: datasource
name: "OutgoingStock"
spec:
  name: "OutgoingStock"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [ 1 ]
  eventType: genericDecisions
  input:
    - object: "ringResourceOrder"
      number: 1
      lastState: ""
      size:
  eventData:
    - activity: "retrieve resources ring"
      type: oc
      output:
        - object: "ringGold"
          number: 1
          change: ""
          size:
      duration: 3
      transition: "ForgingA"