kind: datasource
name: "OutgoingStocka"
spec:
  name: "OutgoingStocka"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [ 1 ]
  eventType: genericDecisions
  input:
    - object: "earringResourceOrder"
      number: 1
      lastState: ""
      size:
  eventData:
    - activity: "retrieve resources earrings"
      type: oc
      output:
        - object: "earringGold"
          number: 2
          change: ""
          size:
        - object: "stone"
          number: 2
          change: ""
          size:
      duration: 8
      transition: "ForgingB"