kind: datasource
name: "Assembly"
spec:
  name: "Assembly"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [ 0.9, 0.1 ]
  eventType: genericDecisions
  input:
    - object: "earringGold"
      number: 2
      lastState: "earring_shaped"
      size:
    - object: "stone"
      number: 2
      lastState: ""
      size:
  eventData:
    - activity: "Assembling completed"
      type: oc
      output:
        - object: "earring"
          number: 2
          change: "assembled"
          size:
      duration: 10
      transition: "ShippingB"
    - activity: "Failure: Item broke"
      type: oc
      output:
        - object: "earring"
          number: 2
          change: "broke"
          size:
      transition: ""
      duration: 2