kind: datasource
name: "DrillingBar"
spec:
  name: "DrillingBar"
  group: "factory"
  type: objectCentric
  workforce: hasWorkforce
  start: "M"
  end: "M"
  workstation: "M"
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "bar"
      number: 1
      lastState: "divided Resource"
      size:
        length: "2"
        width: ""
        depth: ""
  workforces:
    - workforce: "machineWorker"
      number: 1
  eventData:
    - activity: "Drilled"
      output:
        - object: "bar"
          number: 1
          change: "drilled"
          size:
            length: "2"
            width: ""
            depth: ""
      transition: "SandingBar"
      duration: 3
      type: oc