kind: datasource
name: "SandingBoard"
spec:
  name: "SandingBoard"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "board"
      number: 1
      lastState: "divided Resource"
      size:
        length: ""
        width: "5"
        depth: "5"
  eventData:
    - activity: "Sanded board"
      output:
        - object: "board"
          number: 1
          change: "sanded"
          size:
            length: ""
            width: "5"
            depth: "5"
      transition: "TransportM1AB"
      duration: 2
      type: oc