kind: datasource
name: "Shipping"
spec:
  name: "Shipping"
  group: "factory"
  type: objectCentric
  workforce: noWorkforce
  start: "S"
  end: "S"
  workstation: "S"
  selection: genericProbability
  distribution: [ 1.0 ]
  input:
    - object: "woodShelf"
      number: 1
      lastState: "proofed"
      size:
  eventData:
    - activity:
        name: "Package sent"
        output:
          - object: "woodShelf"
            number: 1
            change: "sent"
            size:
      transition: ""
      duration: 5