kind: datasource
name: "TransportM1AB"
spec:
  name: "TransportM1AB"
  group: "transport"
  type: objectCentric
  workforce: hasWorkforce
  workstation: "R"
  start: "M"
  end: "A"
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "board"
      number: 6
      lastState: "sanded"
      size:
        length: ""
        width: "5"
        depth: "5"
  workforces:
    - workforce: "transportRobot"
      number: 1
  eventData:
    - activity: "transport: M1 -> assembly"
      output:
        - object: "board"
          number: 6
          change: "sanded"
          size:
            length: ""
            width: "5"
            depth: "5"
        - object: "handoverBoard"
          number: 1
          change: ""
          size:
      transition: "Assembly"
      duration: 1
      type: oc
