kind: datasource
name: "Order"
spec:
  name: "Order"
  group: "factory"
  selection: genericProbability
  distribution: [1.0]
  eventData:
    -activities:
      - activity: ""
        transition: "OutgoingStock"
        duration: 0
        output:
          - object:
            name: "order"
            number: "1"