kind: datasource
name: "SawingBoard"
spec:
  name: "SawingBoard"
  group: "factory"
  selection: genericProbability
  distribution: [1.0]
  input:
    - object:
      name: "boardResource"
      number: 1
  eventData:
    - activities:
      - activity: "Sawed"
        transition: "DrillingBoard"
        duration: 5
        output:
          - object:
            name: "board"
            number: 4