kind: datasource
name: "DrillingBoard"
spec:
  name: "DrillingBoard"
  group: "factory"
  selection: genericProbability
  distribution: [1.0]
  input:
    - object:
      name: "board"
      number: 1
  eventData:
    - activities:
      - activity: "Drilled"
        transition: "SandingBoard"
        duration: 5
        output:
          - object:
            name: "board"
            number: 1