kind: datasource
name: "OutgoingStock"
spec:
  name: "OutgoingStock"
  group: "factory"
  type: objectCentric
  selection: parallel
  eventType: genericDecisions
  input:
    - object: "resourceOrder"
      number: 1
      lastState: ""
      size:
  eventData:
    - activity: "retrieve resources"
      type: oc
      output:
        - object: "gold"
          number: 1
          change: ""
          size:
      duration: 3
      transition: "Forging"