kind: datasource
name: "<start>"
spec:
  name: "<start>"
  group: "factory"
  type: default
  selection: genericProbability
  distribution: [1.0]
  eventType: eventData
  eventData:
    - activity: ""
      type: "case"
      transition: "GoodsDelivery"
      duration: 0