kind: datasource
name: "Packaging"
spec:
  name: "Packaging"
  group: "Packaging"
  type: default
  selection: genericProbability
  distribution: [ 1.0 ]
  eventType: eventData
  eventData:
    - activity: "Packaging completed"
      type: "case"
      transition: "Shipping"
      duration: 3
