kind: datasource
name: "Packaging"
spec:
  name: "Packaging"
  group: "factory"
  selection: genericProbability
  distribution: [ 1.0 ]
  eventData:
    - activity: "Packaging completed"
      transition: "Shipping"
      duration: 3
