kind: datasource
name: "SandingCrossW"
spec:
  name: "SandingCrossW"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "crossW"
      number: 1
      lastState: "divided Resource"
      size:
        length: "20"
        width: ""
        depth: ""
  eventData:
    - activity: "Sanded"
      type: oc
      output:
        - object: "crossW"
          number: 1
          change: "sanded"
          size:
            length: "20"
            width: ""
            depth: ""
      transition: ""
      duration: 2
