kind: datasource
name: "SandingCrossW"
spec:
  name: "SandingCrossW"
  group: "factory"
  type: objectCentric
  workforce: hasWorkforce
  start: "W"
  end: "W"
  workstation: "W"
  selection: genericProbability
  distribution: [1.0]
  input:
    - object: "crossW"
      number: 1
      lastState: "divided Resource"
      size:
        length: "20"
        width: ""
        depth: ""
  workforces:
    - workforce: "machineWorker"
      number: 1
  eventData:
    - activity:
        name: "Sanded"
        output:
          - object: "crossW"
            number: 1
            change: "sanded"
            size:
              length: "20"
              width: ""
              depth: ""
      transition: ""
      duration: 2
