kind: datasource
name: "SandingBoardA"
spec:
  name: "SandingBoardA"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "boardA"
      number: 1
      lastState: "divided Resource"
      size:
        length: ""
        width: "20"
        depth: "20"
  eventData:
    - activity: "Sanded"
      type: oc
      output:
        - object: "boardA"
          number: 1
          change: "sanded"
          size:
            length: ""
            width: "20"
            depth: "20"
      transition: ""
      duration: 2