kind: datasource
name: "SandingCrossA"
spec:
  name: "SandingCrossA"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "crossA"
      number: 1
      lastState: "drilled"
      size:
        length: "190"
        width: ""
        depth: ""
  eventData:
    - activity: "Sanded"
      type: oc
      output:
        - object: "crossA"
          number: 1
          change: "sanded"
          size:
            length: "190"
            width: ""
            depth: ""
      transition: ""
      duration: 2
