kind: datasource
name: "Assembly1"
spec:
  name: "Assembly1"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [ 0.94, 0.03, 0.03 ]
  eventType: genericDecisions
  input:
    - object: "barA"
      number: 4
      lastState: "sanded"
      size:
        length: "180"
        width: ""
        depth: ""
    - object: "crossA"
      number: 6
      lastState: "sanded"
      size:
        length: "190"
        width: ""
        depth: ""
    - object: "boardW"
      number: 5
      lastState: "sanded"
      size:
        length: ""
        width: "40"
        depth: "30"
    - object: "screw1"
      number: 15
      lastState: ""
      size:
    - object: "pinW"
      number: 20
      lastState: ""
      size:
    - object: "handoverBoard"
      number: 1
      lastState: ""
      size:
    - object: "handoverBarA"
      number: 1
      lastState: ""
      size:
    - object: "handover"
      number: 1
      lastState: ""
      size:
  eventData:
    - activity: "Assembling completed"
      type: oc
      output:
        - object: "shelf1"
          number: 1
          change: "assembled"
          size:
      duration: 15
      transition: "QualityControl1"
    - activity: "Failure: Overheating"
      type: oc
      output:
        - object: "shelf1"
          number: 1
          change: "overheated"
          size:
      transition: ""
      duration: 2
    - activity: "Failure: Item broke"
      type: oc
      output:
        - object: "shelf1"
          number: 1
          change: "broke"
          size:
      transition: ""
      duration: 1