kind: datasource
name: "TransportM1BA"
spec:
  name: "TransportM1BA"
  group: "transport"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "boardAResource"
      number: 1
      lastState: ""
      size:
        length: ""
        width: "60"
        depth: "60"
  eventData:
    - activity: "transport: stock -> MA"
      type: oc
      output:
        - object: "boardAResource"
          number: 1
          change: ""
          size:
            length: ""
            width: "60"
            depth: "60"
        - object: "handoverBoardRA"
          number: 1
          change: ""
          size:
      transition: "SawingBoardA"
      duration: 1
