kind: datasource
name: "TransportSA"
spec:
  name: "TransportSA"
  group: "transport"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "screw1"
      number: 15
      lastState: ""
      size:
    - object: "pinW"
      number: 20
      lastState: ""
      size:
  eventData:
    - activity: "transport: stock -> assembly"
      type: oc
      output:
        - object: "screw1"
          number: 15
          change: ""
          size:
        - object: "pinW"
          number: 20
          change: ""
          size:
        - object: "handover"
          number: 1
          change: ""
          size:
      transition: "Assembly"
      duration: 2
