kind: datasource
name: "TransportMAlA"
spec:
  name: "TransportMAlA"
  group: "transport"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "barA"
      number: 4
      lastState: "sanded"
      size:
        length: "180"
        width: ""
        depth: ""
    - object: "crossA"
      number: 6
      lastState: "sanded"
      size:
        length: "190"
        width: ""
        depth: ""
  eventData:
    - activity: "transport: MA -> assembly"
      type: oc
      output:
        - object: "barA"
          number: 4
          change: "sanded"
          size:
            length: "180"
            width: ""
            depth: ""
        - object: "crossA"
          number: 6
          change: "sanded"
          size:
            length: "190"
            width: ""
            depth: ""
        - object: "handoverBarA"
          number: 1
          change: ""
          size:
      transition: "Assembly"
      duration: 1
