kind: datasource
name: "TransportSAAl"
spec:
  name: "TransportSAAl"
  group: "transport"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "screw2"
      number: 8
      lastState: ""
      size:
    - object: "pinA"
      number: 24
      lastState: ""
      size:
  eventData:
    - activity: "transport: stock -> assembly"
      type: oc
      output:
        - object: "screw2"
          number: 8
          change: ""
          size:
        - object: "pinA"
          number: 24
          change: ""
          size:
        - object: "handoverA"
          number: 1
          change: ""
          size:
      transition: "Assembly"
      duration: 2
