kind: datasource
name: "Shipping"
spec:
  name: "Shipping"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [0.1, 0.9]
  eventType: genericDecisions
  input:
    - object: "gold"
      number: 1
      lastState: "shaped"
      size:
  eventData:
    - activity: "Package waits for sending"
      type: oc
      output:
        - object: "gold"
          number: 1
          change: "shaped"
          size:
      transition: "Shipping"
      duration: 20
    - activity: "Package sent"
      type: oc
      output:
        - object: "gold"
          number: 1
          change: "shipped"
          size:
      transition: ""
      duration: 1