kind: sink
name: ocelConsole
spec:
  type: ocel
  id: "Sensor"
  dataSourceRefs:
    - "GoodsDelivery"
    - "MaterialPreparation"
    - "AssemblyLineSetup"
    - "Assembling"
    - "QualityControl"
    - "Packaging"
    - "Shipping"
    - "OutgoingStock"
    - "OutgoingStockA"
    - "Assembly"
    - "Assembly1"
    - "Assembly2"
    - "SawingBar"
    - "SawingBarA"
    - "SawingBarW"
    - "DrillingBar"
    - "DrillingBarW"
    - "DrillingBarA"
    - "SandingBar"
    - "SandingBarA"
    - "SandingBarW"
    - "OrderPlacement"
    - "OrderPlacementA"
    - "TransportM1"
    - "TransportM1Bar"
    - "TransportM1A"
    - "TransportM1ABar"
    - "TransportSA"
    - "Forging"
    - "ForgingA"
    - "ForgingB"
    - "ShippingA"
    - "ShippingB"
    - "Shipping1"
    - "Shipping2"
    - "SawingBoard"
    - "SawingBoardA"
    - "SawingBoardW"
    - "DrillingBoard"
    - "SandingBoard"
    - "SandingBoardW"
    - "SandingBoardA"
    - "QualityControl"
    - "QualityControl1"
    - "QualityControl2"
    - "A"
    - "B"
    - "C"
    - "D"
    - "E"
    - "TransportM1B"
    - "TransportM1AB"