kind: datasource
name: "OutgoingStock"
spec:
  name: "OutgoingStock"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [ 0.5, 0.5 ]
  eventType: genericDecisions
  input:
    - object: "resourceOrder"
      number: 1
      lastState: ""
      size:
  eventData:
    - activity: "retrieve resources ring"
      type: oc
      output:
        - object: "gold"
          number: 1
          change: ""
          size:
      duration: 3
      transition: "ForgingA"
    - activity: "retrieve resources earrings"
      type: oc
      output:
        - object: "gold"
          number: 2
          change: ""
          size:
        - object: "stone"
          number: 2
          change: ""
          size:
      duration: 8
      transition: "ForgingB"