kind: datasource
name: "SandingBar"
spec:
  name: "SandingBar"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "bar"
      number: 1
      lastState: "drilled"
      size:
        length: "2"
        width: ""
        depth: ""
  eventData:
    - activity: "Sanded bar"
      type: oc
      type: "oc"
      output:
        - object: "bar"
          number: 1
          change: "sanded"
          size:
            length: "2"
            width: ""
            depth: ""
      transition: "TransportM1A"
      duration: 2
