kind: datasource
name: "TransportM1A"
spec:
  name: "TransportM1A"
  group: "transport"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "bar"
      number: 4
      lastState: "sanded"
      size:
        length: "2"
        width: ""
        depth: ""
  eventData:
    - activity: "transport: M1 -> assembly"
      type: oc
      type: "oc"
      output:
        - object: "bar"
          number: 4
          change: "sanded"
          size:
            length: "2"
            width: ""
            depth: ""
        - object: "handoverBar"
          number: 1
          change: ""
          size:
      transition: "Assembly"
      duration: 1
