kind: datasource
name: "TransportSA"
spec:
  name: "TransportSA"
  group: "transport"
  type: objectCentric
  workforce: hasWorkforce
  workstation: "R"
  start: "ST"
  end: "A"
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "screw"
      number: 13
      lastState: ""
      size:
    - object: "bolt"
      number: 13
      lastState: ""
      size:
  workforces:
    - workforce: "transportRobot"
      number: 1
  eventData:
    - activity: "transport: stock -> assembly"
      type: "oc"
      output:
        - object: "screw"
          number: 13
          change: ""
          size:
        - object: "bolt"
          number: 13
          change: ""
          size:
        - object: "handover"
          number: 1
          change: ""
          size:
      transition: "Assembly"
      duration: 2
