kind: datasource
name: "<start>"
spec:
  name: "<start>"
  group: "concept-drift"
  selection: genericProbability
  distribution: [1.0]
  eventData:
    - activity: ""
      transition: "A"
      duration: 0