kind: datasource
name: "OutgoingStock"
spec:
  name: "OutgoingStock"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "resourceOrder"
      number: 1
      lastState: ""
      size:
    - object: "resourceOrder2"
      number: 1
      lastState: ""
      size:
  eventData:
    - activity: "retrieve resources"
      output:
        - object: "gold"
          number: 1
          change: ""
          size:
        - object: "whitegold"
          number: 1
          change: ""
          size:
        - object: "silver"
          number: 1
          change: ""
          size:
        - object: "stone"
          number: 1
          change: ""
          size:
        - object: "diamond"
          number: 1
          change: ""
          size:
        - object: "smaragd"
          number: 1
          change: ""
          size:
        - object: "rubin"
          number: 1
          change: ""
          size:
      duration: 3
      transition: "Forging"
      type: oc