kind: datasource
name: "TransportSAAl"
spec:
  name: "TransportSAAl"
  group: "transport"
  type: objectCentric
  workforce: hasWorkforce
  workstation: "R"
  start: "ST"
  end: "A"
  selection: genericProbability
  distribution: [1.0]
  input:
    - object: "screw2"
      number: 13
      lastState: ""
      size:
    - object: "pinA"
      number: 13
      lastState: ""
      size:
  workforces:
    - workforce: "transportRobot"
      number: 1
  eventData:
    - activity:
        name: "transport: stock -> assembly"
        output:
          - object: "screw2"
            number: 13
            change: ""
            size:
          - object: "pinA"
            number: 13
            change: ""
            size:
          - object: "handover"
            number: 1
            change: "A"
            size:
      transition: "Assembly"
      duration: 2
