kind: datasource
name: "Assembly2"
spec:
  name: "Assembly2"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [ 0.94, 0.03, 0.03 ]
  eventType: genericDecisions
  input:
    - object: "barW"
      number: 4
      lastState: "sanded"
      size:
        length: "2"
        width: ""
        depth: ""
    - object: "boardA"
      number: 6
      lastState: "sanded"
      size:
        length: ""
        width: "5"
        depth: "5"
    - object: "screw2"
      number: 13
      lastState: ""
      size:
    - object: "pinA"
      number: 13
      lastState: ""
      size:
    - object: "handoverBoardA"
      number: 1
      lastState: ""
      size:
    - object: "handoverBar"
      number: 1
      lastState: ""
      size:
    - object: "handoverA"
      number: 1
      lastState: ""
      size:
  eventData:
    - activity: "Assembling completed"
      type: oc
      output:
        - object: "shelf2"
          number: 1
          change: "assembled"
          size:
      duration: 15
      transition: "QualityControl2"
    - activity: "Failure: Overheating"
      type: oc
      output:
        - object: "shelf2"
          number: 1
          change: "overheated"
          size:
      transition: ""
      duration: 2
    - activity: "Failure: Item broke"
      type: oc
      output:
        - object: "shelf2"
          number: 1
          change: "broke"
          size:
      transition: ""
      duration: 1