kind: datasource
name: "C"
spec:
  name: "C"
  group: "line"
  selection: genericProbability
  distribution: [1.0]
  eventType: eventData
  eventData:
    - activity: "C"
      type: "case"
      transition: "D"
      duration: 1