kind: datasource
name: "Forging"
spec:
  name: "Forging"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "gold"
      number: 1
      lastState: ""
      size:
    - object: "whitegold"
      number: 1
      lastState: ""
      size:
  eventData:
    - activity: "Forged"
      output:
        - object: "ring"
          number: 1
          change: "shaped"
          size:
      transition: ""
      duration: 5
      type: oc