kind: datasource
name: "<start>"
spec:
  name: "<start>"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  input:
    - object: "order"
      number: 1
  eventData:
    - activity:
        name: ""
        output:
          - object: "order"
            number: "1"
      transition: "OutgoingStock"
      duration: 0
