kind: datasource
name: "<start>"
spec:
  name: "<start>"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "order"
      number: 1
      lastState: ""
  eventData:
    - activity: ""
      type: oc
      output:
        - object: "order"
          number: "1"
          change: ""
      transition: "OutgoingStock"
      duration: 0
