kind: datasource
name: "OutgoingStock"
spec:
  name: "OutgoingStock"
  group: "factory"
  type: objectCentric
  selection: parallel
  workstation: "OutgoingStock"
  input:
    - object: "order"
      number: 1
      lastState: ""
  eventData:
    - activity:
        name: "retrieve resources"
        type: "objectCentric"
        output:
          - object: "barResource"
            number: 1
            change: ""
          - object: "screw"
            number: 13
            change: ""
      duration: 3
      transition: "<routing>"