kind: datasource
name: "OutgoingStock"
spec:
  name: "OutgoingStock"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [0.5, 0.5]
  input:
    - object: "order"
      number: 1
  eventData:
    - activity:
        name: "Sent to sawing machine"
        output:
          - object: "barResource"
            number: 1
      duration: 3
      transition: "SawingBar"
    - activity:
        name: "Sent to assembly station"
        output:
          - object: "screw"
            number: 13
      duration: 2
      transition: "Assembly"