kind: datasource
name: "SawingBar"
spec:
  name: "SawingBar"
  group: "factory"
  selection: genericProbability
  distribution: [1.0]
  input:
    - object:
      name: "barResource"
      number: 1
  eventData:
    - activities:
      - activity: "Sawed"
        transition: "DrillingBar"
        duration: 5
        output:
          - object:
            name: "bar"
            number: 4