kind: datasource
name: "SawingBar"
spec:
  name: "SawingBar"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  input:
    - object: "barResource"
      number: 1
  eventData:
    - activity:
        name: "Sawed"
        output:
          - object: "bar"
            number: 4
      transition: "DrillingBar"
      duration: 5