kind: datasource
name: "SandingBar"
spec:
  name: "SandingBar"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  workstation: "SandingBar"
  input:
    - object: "bar"
      number: 1
      lastState: "drilled"
  eventData:
    - activity:
        name: "Sanded bar"
        type: "objectCentric"
        output:
          - object: "bar"
            number: 1
            change: "sanded"
      transition: "Assembly"
      duration: 5
