kind: datasource
name: "SandingBar"
spec:
  name: "SandingBar"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  input:
    - object: "bar"
      number: 1
  eventData:
    - activity:
        name: "Sanded bar"
        output:
          - object: "bar"
            number: 1
      transition: "Assembly"
      duration: 5
