kind: datasource
name: "Assembly"
spec:
  name: "Assembly"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [ 0.8, 0.1, 0.1 ]
  input:
    - object: "bar"
      number: 4
      lastState: "sanded"
    - object: "screw"
      number: 13
      lastState: ""
  eventData:
    - activity:
        name: "Assembling completed"
        type: "object"
        output:
          - object: "woodShelf"
            number: 1
            change: "assembled"
      duration: 10
      transition: "Shipping"
    - activity:
        name: "Overheating"
        type: "object"
        output:
          - object: "woodShelf"
            number: 1
            change: "overheated"
      transition: "<end>"
      duration: 2
    - activity:
        name: "Item broke"
        type: "object"
        output:
          - object: "woodShelf"
            number: 1
            change: "broke"
      transition: "<end>"
      duration: 1