ind: datasource
name: "Assembly"
spec:
  name: "Assembly"
  group: "factory"
  selection: genericProbability
  distribution: [ 0.8, 0.1, 0.1 ]
  input:
    - object:
      name: "bar"
      number: 4
    - object:
      name: "screw"
      number: 13
  eventData:
    - activities:
      - activity: "Assembling completed"
        duration: 10
        transition: "QualityControl"
        output:
          - object:
            name: "woodShelf"
            number: 1
    - activities:
      - activity: "Overheating"
        transition: "<end>"
        duration: 2
    - activities:
      - activity: "Item broke"
        transition: "<end>"
        duration: 1