kind: datasource
name: "Shipping"
spec:
  name: "Shipping"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [ 0.8, 0.2 ]
  eventType: genericDecisions
  input:
    - object: "woodShelf"
      number: 1
      lastState: ""
  eventData:
    - activity: "Package waits for sending"
      type: oc
      output:
        - object: "woodShelf"
          number: 1
          change: ""
      transition: "Shipping"
      duration: 180
    - activity: "Package sent"
      type: oc
      output:
        - object: "woodShelf"
          number: 1
          change: ""
      transition: "<end>"
      duration: 1