kind: route
name: "default"
spec:
  routes:
    - routeForActivity: "Sent to sawing machine"
      start: "OutgoingStock"
      end: "SawingBar"
      transferObjects:
        - name: "barResource"
          number: 1
      duration: 3
    - routeForActivity: "Sent to assembly station"
      start: "OutgoingStock"
      end: "Assembly"
      transferObjects:
        - name: "screw"
          number: 13
      duration: 3