kind: stock
name: "default"
spec:
  stocks:
    - object: "order"
      number: 100
      lastState:
    - object: "barResource"
      number: 100
      lastState:
    - object: "screw"
      number: 500
      lastState:
    - object: "bar"
      number: 200
      lastState: "sanded"