kind: object
name: "woodShelf"
spec:
  name: "woodShelf"
  type: "product"
  input: 
    - object: "bar"
      number: 4
      lastState: "sanded"
    - object: "screw"
      number: 13
      lastState: ""
  length: ""
  width: ""