kind: datasource
name: "QualityControl"
spec:
  name: "QualityControl"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [ 0.76, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01 ]
  eventType: genericDecisions
  input:
    - object: "order"
      number: 1
      lastState: ""
      size:
  eventData:
    - activity: "order for resource1"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource2"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource3"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource4"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource5"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource1a"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource2a"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource3a"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource4a"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource5a"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource1b"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource2b"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource3b"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource4b"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource5b"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource1c"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource2c"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource3c"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource4c"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource5c"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource1d"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource2d"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource3d"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource4d"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource5d"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0