kind: datasource
name: "OutgoingStock"
spec:
  name: "OutgoingStock"
  group: "factory"
  type: objectCentric
  workforce: noWorkforce
  start: "ST"
  end: "ST"
  workstation: "ST"
  selection: parallel
  input:
    - object: "resourceOrder1"
      number: 1
      lastState: ""
      size:
  eventData:
    - activity:
        name: "retrieve resources"
        output:
          - object: "barAResource"
            number: 2
            change: ""
            size:
              length: "4"
              width: ""
              depth: ""
          - object: "boardWResource"
            number: 1
            change: ""
            size:
              length: ""
              width: "30"
              depth: "30"
          - object: "screw1"
            number: 13
            change: ""
            size:
          - object: "pinW"
            number: 13
            change: ""
            size:
      duration: 5
      transition: ""