kind: datasource
name: "SawingBarA"
spec:
  name: "SawingBarA"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "barAResource"
      number: 2
      lastState: ""
      size:
        length: "4"
        width: ""
        depth: ""
    - object: "handoverBarRA"
      number: 1
      lastState: ""
      size:
  eventData:
    - activity: "Sawed"
      type: oc
      output:
        - object: "barA"
          number: 4
          change: "divided Resource"
          size:
            length: "2"
            width: ""
            depth: ""
      transition: "DrillingBarA"
      duration: 4