kind: datasource
name: "SandingBarW"
spec:
  name: "SandingBarW"
  group: "factory"
  type: objectCentric
  workforce: noWorkforce
  start: "W"
  end: "W"
  workstation: "W"
  selection: genericProbability
  distribution: [1.0]
  input:
    - object: "barW"
      number: 1
      lastState: "drilled"
      size:
        length: "2"
        width: ""
        depth: ""
  eventData:
    - activity:
        name: "Sanded"
        output:
          - object: "barW"
            number: 1
            change: "sanded"
            size:
              length: "2"
              width: ""
              depth: ""
      transition: "Assembly2"
      duration: 2
