kind: datasource
name: "Shipping2"
spec:
  name: "Shipping2"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [ 1.0 ]
  eventType: genericDecisions
  input:
    - object: "shelf2"
      number: 1
      lastState: "proofed"
      size:
  eventData:
    - activity: "Package sent"
      type: oc
      output:
        - object: "shelf2"
          number: 1
          change: "sent"
          size:
      transition: ""
      duration: 5