kind: datasource
name: "TransportMW"
spec:
  name: "TransportMW"
  group: "transport"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "barWResource"
      number: 2
      lastState: ""
      size:
        length: "4"
        width: ""
        depth: ""
  eventData:
    - activity: "transport: stock -> MW"
      type: oc
      output:
        - object: "barWResource"
          number: 2
          change: ""
          size:
            length: "4"
            width: ""
            depth: ""
        - object: "handoverBarR"
          number: 1
          change: ""
          size:
      transition: "SawingBarW"
      duration: 1
