kind: datasource
name: "Shipping"
spec:
  name: "Shipping"
  group: "factory"
  type: objectCentric
  workforce: noWorkforce
  start: "K"
  end: "K"
  workstation: "K"
  selection: genericProbability
  distribution: [1.0]
  input:
    - object: "order"
      number: 1
      lastState: ""
      size:
  eventData:
    - activity:
        name: "order for resources"
        output:
          - object: "resourceOrder"
            number: 1
            change: ""
            size:
      transition: "OutgoingStock"
      duration: 0