numberOfDataSources:
  type: static
  count: 9
caseId: increasing
type: load
loadType: gradual
tickCount: 100
load: 10
minimalLoad: 5
dataSourceTopology:
  defaultSink:
    type: kafka
    bootstrapServer: kube1-1:30376
    topic: t5
    partition:
      type: caseId
      numberPartitions: 1
    validationTopic: assembly-validation
    validationSplit: 8
  dataSources:
    - name: "GoodsDelivery"             #pseudo Transition 0 from start to "store"
      eventGeneration:
        selection: genericProbability
        distribution: [0.01, 0.91, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
        from:
          events:
            - activity: "Reject"
              duration: 1
              transition: 10
            - activity: "Store"
              transition: 1
              duration: 5
            - activity: "Pass To Production"
              duration: 4
              transition: 2
            - activity: "Material Preparation Finished"
              duration: 1
              transition: 3
            - activity: "Internal Error"
              transition: 4
              duration: 5
            - activity: "Assemble complete"
              duration: 7
              transition: 5
            - activity: "Waiting for Material"
              duration: 1
              transition: 6
            - activity: "Packaging completed"
              transition: 7
              duration: 4
            - activity: "Waiting for sending"
              duration: 1
              transition: 8
            - activity: "Package sent"
              duration: 1
              transition: 9

    - name: "GoodsProcessing"       #Transition 1 from store to "pass to production / reject"
      eventGeneration:
        selection: genericProbability
        distribution: [0.11, 0.00, 0.82, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
        from:
          events:
            - activity: "Reject"
              duration: 1
              transition: 10
            - activity: "Store"
              transition: 1
              duration: 5
            - activity: "Pass To Production"
              duration: 4
              transition: 2
            - activity: "Material Preparation Finished"
              duration: 1
              transition: 3
            - activity: "Internal Error"
              transition: 4
              duration: 5
            - activity: "Assemble complete"
              duration: 7
              transition: 5
            - activity: "Waiting for Material"
              duration: 1
              transition: 6
            - activity: "Packaging completed"
              transition: 7
              duration: 4
            - activity: "Waiting for sending"
              duration: 1
              transition: 8
            - activity: "Package sent"
              duration: 1
              transition: 9

    - name: "MaterialCompletion"       #Transition 2 from "pass to production" to  "Material Prep finished / Waiting for Material"
      eventGeneration:
        selection: genericProbability
        distribution: [0.01, 0.00, 0.01, 0.2, 0.01, 0.01, 0.73, 0.01, 0.01, 0.01]
        from:
          events:
            - activity: "Reject"
              duration: 1
              transition: 10
            - activity: "Store"
              transition: 1
              duration: 5
            - activity: "Pass To Production"
              duration: 4
              transition: 2
            - activity: "Material Preparation Finished"
              duration: 1
              transition: 3
            - activity: "Internal Error"
              transition: 4
              duration: 5
            - activity: "Assemble complete"
              duration: 7
              transition: 5
            - activity: "Waiting for Material"
              duration: 1
              transition: 6
            - activity: "Packaging completed"
              transition: 7
              duration: 4
            - activity: "Waiting for sending"
              duration: 1
              transition: 8
            - activity: "Package sent"
              duration: 1
              transition: 9

    - name: "AssemblyProcess"         #Transition 3 from Material Preparation Finished  to "Internal Error / Assemble complete"
      eventGeneration:
        selection: genericProbability
        distribution: [0.01, 0.00, 0.00, 0.01, 0.06, 0.88, 0.01, 0.01, 0.01, 0.01]
        from:
          events:
            - activity: "Reject"
              duration: 1
              transition: 10
            - activity: "Store"
              transition: 1
              duration: 5
            - activity: "Pass To Production"
              duration: 4
              transition: 2
            - activity: "Material Preparation Finished"
              duration: 1
              transition: 3
            - activity: "Internal Error"
              transition: 4
              duration: 5
            - activity: "Assemble complete"
              duration: 7
              transition: 5
            - activity: "Waiting for Material"
              duration: 1
              transition: 6
            - activity: "Packaging completed"
              transition: 7
              duration: 4
            - activity: "Waiting for sending"
              duration: 1
              transition: 8
            - activity: "Package sent"
              duration: 1
              transition: 9

    - name: "QualityControl"          #Transition 4 Internal Error to  "Waiting for material"
      eventGeneration:
        selection: genericProbability
        distribution: [0.01, 0.00, 0.00, 0.00, 0.02, 0.01, 0.93, 0.01, 0.01, 0.01]
        from:
          events:
            - activity: "Reject"
              duration: 1
              transition: 10
            - activity: "Store"
              transition: 1
              duration: 5
            - activity: "Pass To Production"
              duration: 4
              transition: 2
            - activity: "Material Preparation Finished"
              duration: 1
              transition: 3
            - activity: "Internal Error"
              transition: 4
              duration: 5
            - activity: "Assemble complete"
              duration: 7
              transition: 5
            - activity: "Waiting for Material"
              duration: 1
              transition: 6
            - activity: "Packaging complete"
              transition: 7
              duration: 4
            - activity: "Waiting for sending"
              duration: 1
              transition: 8
            - activity: "Package sent"
              duration: 1
              transition: 9

    - name: "Assembly"               #Transition 5 Assemble complete to "Packaging complete"
      eventGeneration:
        selection: genericProbability
        distribution: [0.01, 0.00, 0.00, 0.00, 0.00, 0.01, 0.00, 0.96, 0.01, 0.01]
        from:
          events:
            - activity: "Reject"
              duration: 1
              transition: 10
            - activity: "Store"
              transition: 1
              duration: 5
            - activity: "Pass To Production"
              duration: 4
              transition: 2
            - activity: "Material Preparation Finished"
              duration: 1
              transition: 3
            - activity: "Internal Error"
              transition: 4
              duration: 5
            - activity: "Assemble complete"
              duration: 7
              transition: 5
            - activity: "Waiting for Material"
              duration: 1
              transition: 6
            - activity: "Packaging completed"
              transition: 7
              duration: 4
            - activity: "Waiting for sending"
              duration: 1
              transition: 8
            - activity: "Package sent"
              duration: 1
              transition: 9

    - name: "Packing"                #Transition 6 Waiting for Material to "Pass to production"
      eventGeneration:
        selection: uniform
        distribution: [0.01, 0.00, 0.92, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
        from:
          events:
            - activity: "Reject"
              duration: 1
              transition: 10
            - activity: "Store"
              transition: 1
              duration: 5
            - activity: "Pass To Production"
              duration: 4
              transition: 2
            - activity: "Material Preparation Finished"
              duration: 1
              transition: 3
            - activity: "Internal Error"
              transition: 4
              duration: 5
            - activity: "Assemble complete"
              duration: 7
              transition: 5
            - activity: "Waiting for Material"
              duration: 1
              transition: 6
            - activity: "Packaging complete"
              transition: 7
              duration: 4
            - activity: "Waiting for sending"
              duration: 1
              transition: 8
            - activity: "Package sent"
              duration: 1
              transition: 9

    - name: "Shipping"                #Transition 7 Packaging completed to "Waiting for sending"
      eventGeneration:
        selection: uniform
        distribution: [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.98, 0.02]
        from:
          events:
            - activity: "Reject"
              duration: 1
              transition: 10
            - activity: "Store"
              transition: 1
              duration: 5
            - activity: "Pass To Production"
              duration: 4
              transition: 2
            - activity: "Material Preparation Finished"
              duration: 1
              transition: 3
            - activity: "Internal Error"
              transition: 4
              duration: 5
            - activity: "Assemble complete"
              duration: 7
              transition: 5
            - activity: "Waiting for Material"
              duration: 1
              transition: 6
            - activity: "Packaging complete"
              transition: 7
              duration: 4
            - activity: "Waiting for sending"
              duration: 1
              transition: 8
            - activity: "Package sent"
              duration: 1
              transition: 9

    - name: "Shipping"                #Transition 8 Waiting for sending to "Packaging complete/Package sent"
      eventGeneration:
        selection: uniform
        distribution: [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.15, 0.85]
        from:
          events:
            - activity: "Reject"
              duration: 1
              transition: 10
            - activity: "Store"
              transition: 1
              duration: 5
            - activity: "Pass To Production"
              duration: 4
              transition: 2
            - activity: "Material Preparation Finished"
              duration: 1
              transition: 3
            - activity: "Internal Error"
              transition: 4
              duration: 5
            - activity: "Assemble complete"
              duration: 7
              transition: 5
            - activity: "Waiting for Material"
              duration: 1
              transition: 6
            - activity: "Packaging complete"
              transition: 7
              duration: 4
            - activity: "Waiting for sending"
              duration: 1
              transition: 8
            - activity: "Package sent"
              duration: 1
              transition: 9