numberOfDataSources:
  type: static
  count: 3
caseId: increasing
type: load
loadType: gradual
tickCount: 100
load: 10
minimalLoad: 5
dataSourceTopology:
  defaultSink:
    type: kafka
    bootstrapServer: kube1-1:30376
    topic: t3
    partition:
      type: caseId
      numberPartitions: 1
  dataSources:
  - name: "S1"
    eventGeneration:
      selection: genericProbability
      distribution: [1.0]
      from:
        events:
          - activity: "A1"
            duration: 1
            transition: 1
  - name: "S2"
    eventGeneration:
      selection: genericProbability
      distribution: [ 0.7, 0.3 ]
      from:
        events:
          - activity: "A2"
            duration: 5
            transition: 2
          - activity: "A3"
            duration: 5
            transition: 2
  - name: "S3"
    eventGeneration:
      selection: genericProbability
      distribution: [ 1.0 ]
      from:
        events:
          - activity: "A4"
            duration: 2
            transition: 3

