numberOfDataSources:
  type: static
  count: 7
caseId: increasing
type: load
loadType: constant
tickCount: 100
load: 10
dataSourceTopology:
  defaultSink:
    type: console
  dataSources:
  - name: "GoodsReceiving"
    groupId: "warehouse"
    eventGeneration:
      selection: genericProbability
      distribution: [0.1, 0.6, 0.3]
      from:
        events:
          - activity: "Reject"
            transition: 6
            duration: 1
          - activity: "Store"
            transition: 1
            duration: 1
          - activity: "Repackage"
            transition: 1
            duration:
              type: uniform
              lowerBound: 3
              upperBound: 7
  - name: "Storage"
    groupId: "warehouse"
    eventGeneration:
      selection: genericProbability
      distribution: [ 0.3, 0.7 ]
      from:
        events:
          - activity: "Picked up"
            duration:
              type: uniform
              lowerBound: 1
              upperBound: 2
            transition: 2
          - activity: "Still storing"
            transition: 1
            duration: 1
  - name: "Picking"
    groupId: "warehouse"
    eventGeneration:
      selection: genericProbability
      distribution: [ 0.5, 0.1, 0.4 ]
      from:
        events:
          - activity: "Transport To Storage"
            transition: 1
            duration: 1
          - activity: "Transport To Returns Handling"
            transition: 4
            duration: 1
          - activity: "Transport to shipping"
            transition: 5
            duration:
              type: uniform
              lowerBound: 5
              upperBound: 10
  - name: "Packaging"
    groupId: "warehouse"
    eventGeneration:
      selection: genericProbability
      distribution: [ 1.0 ]
      from:
        events:
          - activity: "Packaging completed"
            transition: 2
            duration: 3
  - name: "ReturnsHandling"
    groupId: "warehouse"
    eventGeneration:
      selection: genericProbability
      distribution: [ 1.0 ]
      from:
        events:
          - activity: "Analysis"
            transition: 2
            duration:
              type: uniform
              lowerBound: 30
              upperBound: 60
  - name: "Shipping"
    groupId: "warehouse"
    eventGeneration:
      selection: uniform
      distribution: [ 0.8, 0.2 ]
      from:
        events:
          - activity: "Package waits for sending"
            transition: 5
            duration: 180
          - activity: "Package sent"
            transition: 6
            duration: 1