kind: datasource
name: "OrderPlacement"
spec:
  name: "OrderPlacement"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "order"
      number: 1
      lastState: ""
  eventData:
    - activity: "order for resources"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
      transition: "OutgoingStock"
      duration: 0
