kind: datasource
name: "OutgoingStock"
spec:
  name: "OutgoingStock"
  group: "factory"
  type: objectCentric
  selection: parallel
  eventType: genericDecisions
  input:
    - object: "resourceOrder"
      number: 1
      lastState: ""
  eventData:
    - activity: "retrieve resources"
      type: oc
      output:
        - object: "barResource"
          number: 1
          change: ""
        - object: "screw"
          number: 13
          change: ""
      duration: 3
      transition: ""