kind: datasource
name: "DrillingBar"
spec:
  name: "DrillingBar"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  input:
    - object: "bar"
      number: 1
      lastState: "divided Resource"
  eventData:
    - activity:
        name: "Drilled"
        output:
          - object: "bar"
            number: 1
            change: "drilled"
      transition: "SandingBar"
      duration: 5