kind: datasource
name: "TransportM1"
spec:
  name: "TransportM1"
  group: "transport"
  type: objectCentric
  workforce: hasWorkforce
  workstation: "R"
  start: "ST"
  end: "M"
  selection: genericProbability
  distribution: [1.0]
  input:
    - object: "boardResource"
      number: 1
      lastState: ""
      size:
        length: ""
        width: "30"
        depth: "30"
  workforces:
    - workforce: "transportRobot"
      number: 1
  eventData:
    - activity:
        name: "transport from stock to M1"
        output:
          - object: "boardResource"
            number: 1
            change: ""
            size:
              length: ""
              width: "30"
              depth: "30"
          - object: "handover"
            number: 1
            change: ""
            size:
      transition: "SawingBar"
      duration: 10
