kind: datasource
name: "B"
spec:
  name: "B"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [0.96, 0.01, 0.01, 0.01, 0.01]
  eventType: genericDecisions
  input:
    - object: "order"
      number: 1
      lastState: ""
      size:
  eventData:
    - activity: "order for resource1"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource2"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource3"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource4"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0
    - activity: "order for resource5"
      type: oc
      output:
        - object: "resourceOrder"
          number: 1
          change: ""
          size:
      transition: "OutgoingStock"
      duration: 0