kind: workforces
name: "default"
spec:
  workforces:
    - name: "humanWorkforce"
      startLocation: "O"
      number: 1
    - name: "humanWorkforce"
      startLocation: "A"
      number: 1
    - name: "humanWorkforce"
      startLocation: "B"
      number: 1
    - name: "humanWorkforce"
      startLocation: "C"
      number: 1
    - name: "humanWorkforce"
      startLocation: "D"
      number: 1