kind: simulation
name: assembly-line-simulation
spec:
  type: loadTest
  steps: 100
  caseId: increasing
  timeframe: 10
  load:
    loadBehavior: gradual
    tickCount: 100
    minimalLoad: 5
    load: 10