kind: datasource
name: "OutgoingStockA"
spec:
  name: "OutgoingStockA"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "resourceOrder2"
      number: 1
      lastState: ""
      size:
  eventData:
    - activity: "retrieve resources"
      output:
        - object: "barWResource"
          number: 2
          change: ""
          size:
            length: "4"
            width: ""
            depth: ""
        - object: "boardAResource"
          number: 1
          change: ""
          size:
            length: ""
            width: "30"
            depth: "30"
        - object: "screw2"
          number: 13
          change: ""
          size:
        - object: "pinA"
          number: 13
          change: ""
          size:
      duration: 5
      transition: ""
      type: oc