kind: datasource
name: "SawingBoardW"
spec:
  name: "SawingBoardW"
  group: "factory"
  type: objectCentric
  workforce: noWorkforce
  start: "W"
  end: "W"
  workstation: "W"
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "boardWResource"
      number: 1
      lastState: ""
      size:
        length: ""
        width: "30"
        depth: "30"
  eventData:
    - activity: "Sawed"
      output:
        - object: "boardW"
          number: 6
          change: "divided Resource"
          size:
            length: ""
            width: "5"
            depth: "5"
      transition: "SandingBoardW"
      duration: 9
      type: oc