kind: datasource
name: "SawingBarW"
spec:
  name: "SawingBarW"
  group: "factory"
  type: objectCentric
  workforce: noWorkforce
  start: "W"
  end: "W"
  workstation: "W"
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "barWResource"
      number: 2
      lastState: ""
      size:
        length: "4"
        width: ""
        depth: ""
  eventData:
    - activity: "Sawed"
      output:
        - object: "barW"
          number: 4
          change: "divided Resource"
          size:
            length: "2"
            width: ""
            depth: ""
      transition: "DrillingBarW"
      duration: 4
      type: oc