kind: datasource
name: "QualityControl1"
spec:
  name: "QualityControl1"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [ 1.0 ]
  eventType: genericDecisions
  input:
    - object: "shelf1"
      number: 1
      lastState: "assembled"
      size:
  eventData:
    - activity: "Quality check passed"
      output:
        - object: "shelf1"
          number: 1
          change: "proofed"
          size:
      transition: "Shipping1"
      duration: 2

      type: oc
