kind: datasource
name: "QualityControl2"
spec:
  name: "QualityControl2"
  group: "factory"
  type: objectCentric
  workforce: noWorkforce
  start: "A"
  end: "A"
  workstation: "A"
  selection: genericProbability
  distribution: [ 1.0 ]
  eventType: genericDecisions
  input:
    - object: "shelf2"
      number: 1
      lastState: "assembled"
      size:
  eventData:
    - activity: "Quality check passed"
      output:
        - object: "shelf2"
          number: 1
          change: "proofed"
          size:
      transition: "Shipping2"
      duration: 2

      type: oc
