kind: route
name: "default"
spec:
  routes:
    - routeForActivity: "Warehouse AL to wood"
      start: "STA"
      end: "W"
      duration: 10
    - routeForActivity: "Warehouse Wood to wood"
      start: "STW"
      end: "W"
      duration: 1
    - routeForActivity: "Warehouse Small to wood"
      start: "STS"
      end: "W"
      duration: 2
    - routeForActivity: "retrieve resources"
      start: "STA"
      end: "Al"
      duration: 1
    - routeForActivity: "retrieve resources"
      start: "STW"
      end: "Al"
      duration: 10
    - routeForActivity: "retrieve resources"
      start: "STS"
      end: "Al"
      duration: 2
    - routeForActivity: "Sent to assembly station"
      start: "STA"
      end: "A"
      duration: 3
    - routeForActivity: "Sent to assembly station"
      start: "STW"
      end: "A"
      duration: 3
    - routeForActivity: "Sent to assembly station"
      start: "STS"
      end: "A"
      duration: 2
    - routeForActivity: "Back to stock"
      start: "A"
      end: "ST"
      duration: 3
    - routeForActivity: "Back to stock"
      start: "A"
      end: "STA"
      duration: 3
    - routeForActivity: "Back to stock"
      start: "A"
      end: "STW"
      duration: 3
    - routeForActivity: "Back to stock"
      start: "A"
      end: "STS"
      duration: 2
    - routeForActivity: "Back to stock"
      start: "W"
      end: "STW"
      duration: 1
    - routeForActivity: "Back to stock"
      start: "W"
      end: "STA"
      duration: 10
    - routeForActivity: "Back to stock"
      start: "W"
      end: "STS"
      duration: 2
    - routeForActivity: "Back to stock"
      start: "Al"
      end: "STW"
      duration: 10
    - routeForActivity: "Back to stock"
      start: "Al"
      end: "STA"
      duration: 1
    - routeForActivity: "Back to stock"
      start: "Al"
      end: "STS"
      duration: 2
    - routeForActivity: "Sent to assembly station"
      start: "W"
      end: "A"
      duration: 1
    - routeForActivity: "Back to machine"
      start: "A"
      end: "W"
      duration: 1
    - routeForActivity: "Sent to assembly station"
      start: "Al"
      end: "A"
      duration: 1
    - routeForActivity: "Back to machine"
      start: "A"
      end: "Al"
      duration: 1
