kind: workforces
name: "default"
spec:
  workforces:
    - name: "transportRobot"
      startLocation: "A"
      number: 8
    - name: "machineWorker"
      startLocation: "W"
      number: 8
    - name: "machineWorker"
      startLocation: "Al"
      number: 8