kind: datasource
name: "SawingBoardW"
spec:
  name: "SawingBoardW"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [0.97, 0.01, 0.02]
  eventType: genericDecisions
  input:
    - object: "boardWResource"
      number: 1
      lastState: ""
      size:
        length: ""
        width: "30"
        depth: "30"
    - object: "handoverBoardR"
      number: 1
      lastState: ""
      size:
  eventData:
    - activity: "Sawed"
      type: oc
      output:
        - object: "boardW"
          number: 6
          change: "divided Resource"
          size:
            length: ""
            width: "5"
            depth: "5"
      transition: "SandingBoardW"
      duration: 9
    - activity: "Failure: Sawing machine broken"
      type: oc
      output:
        - object: "boardWResource"
          number: 1
          change: ""
          size:
            length: ""
            width: "30"
            depth: "30"
        - object: "handoverBoardR"
          number: 1
          change: ""
          size:
      duration: 20
      transition: ""
    - activity: "Failure: One piece broken"
      type: oc
      output:
        - object: "boardW"
          number: 4
          change: "divided Resource"
          size:
            length: ""
            width: "5"
            depth: "5"
        - object: "boardW"
          number: 2
          change: "broken"
          size:
            length: ""
            width: "4.32"
            depth: "4.24"
      duration: 4
      transition: "SandingBoardW"