kind: datasource
name: "QualityControl1"
spec:
  name: "QualityControl1"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [ 0.8, 0.15, 0.05]
  eventType: genericDecisions
  input:
    - object: "shelf1"
      number: 1
      lastState: "assembled"
      size:
  eventData:
    - activity: "Quality check passed"
      type: oc
      output:
        - object: "shelf1"
          number: 1
          change: "proofed"
          size:
      transition: "Shipping1"
      duration: 2
    - activity: "Item Corrections"
      type: oc
      output:
        - object: "shelf1"
          number: 1
          change: "proofed"
          size:
      transition: "Shipping1"
      duration: 12
    - activity: "Failure: Quality Insufficient"
      type: oc
      output:
        - object: "shelf1"
          number: 1
          change: "damaged"
          size:
      transition: ""
      duration: 2

