kind: datasource
name: "ForgingB"
spec:
  name: "ForgingB"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [1.0]
  eventType: genericDecisions
  input:
    - object: "gold"
      number: 1
      lastState: ""
      size:
  eventData:
    - activity: "Forged"
      output:
        - object: "gold"
          number: 1
          change: "earring_shaped"
          size:
      transition: "Assembly"
      duration: 5
      type: oc