kind: datasource
name: "ShippingA"
spec:
  name: "ShippingA"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [ 0.2, 0.8 ]
  eventType: genericDecisions
  input:
    - object: "gold"
      number: 1
      lastState: "ring_shaped"
      size:
  eventData:
    - activity: "Package waits for sending"
      output:
        - object: "gold"
          number: 1
          change: "ring_shaped"
          size:
      transition: "Shipping"
      duration: 20
      type: oc
    - activity: "Package sent"
      output:
        - object: "gold"
          number: 1
          change: "shipped"
          size:
      transition: ""
      duration: 1
      type: oc