kind: datasource
name: "DrillingBar"
spec:
  name: "DrillingBar"
  group: "factory"
  type: objectCentric
  selection: genericProbability
  distribution: [0.99, 0.01]
  eventType: genericDecisions
  input:
    - object: "bar"
      number: 1
      lastState: "divided Resource"
      size:
        length: "2"
        width: ""
        depth: ""
  eventData:
    - activity: "Drilled"
      type: oc
      output:
        - object: "bar"
          number: 1
          change: "drilled"
          size:
            length: "2"
            width: ""
            depth: ""
      transition: "SandingBar"
      duration: 3
    - activity: "Failure: Sawing machine broken"
      type: oc
      output:
        - object: "bar"
          number: 1
          change: "divided Resource"
          size:
            length: "2"
            width: ""
            depth: ""
      duration: 20
      transition: ""