name: Docker Image CI

on:
  push:
    branches: [ "feature/github-actions-docker-build" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build image
      run: docker build . --file Dockerfile --tag hendrikreiter/distributed-event-factory:0.2.0-SNAPSHOT
    - name: Push image
      run: docker push hendrikreiter/distributed-event-factory:0.2.0-SNAPSHOT