kind: datasource
name: "ForgingA"
spec:
  name: "ForgingA"
  group: "factory"
  type: objectCentric
  workforce: hasWorkforce
  start: "M"
  end: "M"
  workstation: "M"
  selection: genericProbability
  distribution: [1.0]
  input:
    - object: "gold"
      number: 1
      lastState: ""
      size:
  workforces:
    - workforce: "humanWorkforce"
      number: 1
  eventData:
    - activity:
        name: "Forged"
        output:
          - object: "gold"
            number: 1
            change: "ring_shaped"
            size:
      transition: "ShippingA"
      duration: 5