kind: route
name: "default"
spec:
  routes:
    - routeForActivity: "retrieve resources"
      start: "ST"
      end: "M"
      transferObjects:
        - name: "barResource"
          number: 1
      duration: 3
    - routeForActivity: "Sent to assembly station"
      start: "ST"
      end: "S"
      transferObjects:
        - name: "screw"
          number: 13
      duration: 3
    - routeForActivity: "Back to stock"
      start: "S"
      end: "ST"
      transferObjects:
        - name: "screw"
          number: 13
      duration: 3
    - routeForActivity: "Back to stock"
      start: "M"
      end: "ST"
      transferObjects:
        - name: "screw"
          number: 13
      duration: 3
    - routeForActivity: "Sent to assembly station"
      start: "M"
      end: "S"
      transferObjects:
        - name: "screw"
          number: 13
      duration: 3
    - routeForActivity: "Back to machine"
      start: "S"
      end: "M"
      transferObjects:
        - name: "screw"
          number: 13
      duration: 3