kind: simulation
name: assembly-line-simulation
spec:
  type: loadTest
  steps: 100
  caseId: increasing
  genTimeframesTilStart: 10
  timeframe: 1000
  maxConcurrentCases: 5
  load:
    loadBehavior: constant
    load: 10